name: mal-sorter
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - flake8
  - flake8-docstrings
  - black
  - ipykernel
  - requests
  - aiohttp
  - beautifulsoup4
  - pandas
